### ISSUE TITLE
Blank mb used displayed in logs

### ISSUE THREAD

**Issue by vcardillo** [schneems/puma_worker_killer#45]
`Rolling Restart. 2 workers consuming total: 761.38330078125 mb out of max:  mb`

`config.ram` is set:
`config.ram           = 7500 # mb`

**Comment by schneems** [comment]
Can you give me an app that reproduces the problem please

**Comment by nritholtz** [comment]
@schneems See https://github.com/nritholtz/puma_worker_killer-45

I put instructions to reproduce in the README.

**Comment by schneems** [comment]
Thanks for the app! I figured out what's going on here is where we're printing that value https://github.com/schneems/puma_worker_killer/blob/master/lib/puma_worker_killer/rolling_restart.rb#L15

We are getting the max ram from `@max_ram`which is never set, and frankly rolling restarts doesn't need to know about. I think this is because I copied and pasted a log statement from somewhere else. We should remove that part of the log statement all together. Do you have time for a PR?

**Comment by schneems** [comment]
Thanks again!
