### ISSUE TITLE
[ruby] <defunct>

### ISSUE THREAD

**Issue by wellington1993** [schneems/puma_worker_killer#75]
Hi,

I like that project but I've got a problem with defunct processes.
After the kill action from gem, the killed ruby processes, still are presents in the process list with pid and with defunct state.

Without clean of that processes can be a problem.
Images:

![puma-defunct-5-htop](https://user-images.githubusercontent.com/6920053/60721761-59b1fb00-9f05-11e9-967f-c5a19c8722a1.png)
![puma-defunct-4-config](https://user-images.githubusercontent.com/6920053/60721762-59b1fb00-9f05-11e9-9592-abb82796c462.png)
![puma-defunct-3-pstree](https://user-images.githubusercontent.com/6920053/60721763-5a4a9180-9f05-11e9-9f14-77ca4c446e94.png)
![puma-defunct-2](https://user-images.githubusercontent.com/6920053/60721764-5a4a9180-9f05-11e9-9f63-19145a209e2f.png)
![puma-defunct-1](https://user-images.githubusercontent.com/6920053/60721765-5a4a9180-9f05-11e9-896c-aa851ac8979d.png)

Thanks!

**Comment by wellington1993** [comment]
I have 214 defunct processes now.
Isn't a big problem because the '/proc/sys/kernel/pid_max' value is 32768.

But if the processes still defuncting maybe will be a problem in the future.

I'm search and apparently the best way to free the defunct process is killing the parent process.
But I don't know a secure way to do this in production environment.

Thanks!

**Comment by schneems** [comment]
Can you manually send a SIGTERM to those processes and have them shut down?

It seems like the issue is there is something preventing the process from shutting down which would likely be a problem in your app code instead of with puma or puma worker killer.

Try running a plain puma process with a “hello world” rack app and see if it still happens. Also make sure puma and PWK are upgraded to the latest.

For the processes that are still alive there might be ways to get them to output where they are stuck. Maybe a tool like rbtrace.

**Comment by wellington1993** [comment]
Thanks @schneems

I will try rbtrace.
Probably my app code and maybe related with threads use.

Closing this issue for now.
